apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-api
  name: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - image: toshiroolangar/python-flask-rest-api-project:latest
        name: python-api
        ports:
          - containerPort: 80
        imagePullPolicy: IfNotPresent