apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-api
  name: python-api-svc
spec:
  ports:
  - port: 9001
    nodePort: 30007
    targetPort: 9001
  selector:
    app: python-api
  type: NodePort