apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 9001
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }}
  type: LoadBalancer