apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 9001
    nodePort: 30007
    targetPort: 9001
  selector:
    app: {{ .Values.appName }}
  type: NodePort